# Generated by Django 4.2.2 on 2023-09-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Category_id',
            new_name='customerReviewRank',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Category_name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Isbn',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Title',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Pub_date',
            new_name='pubDate',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Fixed_price',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
